# Generated by Django 3.0.6 on 2020-05-14 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, unique=True)),
                ('website', models.CharField(max_length=100, null=True)),
                ('careersPage', models.CharField(max_length=100, null=True)),
                ('reviewCount', models.IntegerField(null=True)),
                ('interviewCount', models.IntegerField(null=True)),
                ('salaryCount', models.IntegerField(null=True)),
                ('recommendedPercent', models.FloatField(null=True)),
                ('rating', models.FloatField(null=True)),
            ],
        ),
    ]
